import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
    screen: {
        flex: 1,
        backgroundColor: '#fff',
      },
      actionsContainer: {
        flexDirection: 'row',
        justifyContent: 'space-around',
        marginVertical: 50,
      },
      action: {
        alignItems: 'center',
      },
      container: {
        justifyContent: 'center',
        alignItems: 'center',
        padding: 16,
      },
      amountContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        width: '100%',
        padding: 16,
        //backgroundColor: '#f9f9f9',
        borderRadius: 8,
        shadowColor: '#bbb',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.1,
        shadowRadius: 10,
        elevation: 2,
      },
      card: {
        backgroundColor: '#fff',
        padding: 50, 
        borderRadius: 20, 
        alignItems: 'center',
        width: '25%',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.2,
        shadowRadius: 5,
        elevation: 5,
      },
      creditBox: {
        flex: 1,
      },
      amountText: {
        fontSize: 18,
        fontWeight: 'bold',
      },
      home: {
        backgroundColor: '#F2EFEF',
        flex: 1,
      },
      noticeContainer: {
        padding: 30,
        backgroundColor: '#fff',
        borderRadius: 10,
        marginHorizontal: 50,
        marginVertical: 10,
      },
      statsContainer: {
        flexDirection: 'row',
        justifyContent: 'center',
        marginVertical: 20,
      },
      stat: {
        alignItems: 'center',
        backgroundColor: '#fff',
        padding: 50,  
        borderTopRightRadius: 10,
        borderBottomRightRadius: 10,
        width: '44%',
      },
      stat1: {
        alignItems: 'center',
        backgroundColor: '#fff',
        padding: 50,  
        borderTopLeftRadius: 10,
        borderBottomLeftRadius: 10,
        width: '44%',
      },
      statNumber: {
        fontSize: 24,
        fontWeight: 'bold',
      },
      statText: {
        justifyContent: 'center',
        fontSize: 16,
        fontWeight: 'bold',
      },
      selectButton: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        position: 'absolute',
        bottom: 20,
        left: 20, 
        right: 20, 
        padding: 5,
        marginLeft: 500,
        backgroundColor: '#0000FF',
        borderRadius: 30,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.2,
        shadowRadius: 5,
        elevation: 5,
      },
      selectButtonText: {
        color: '#fff',
        fontSize: 16,
        fontWeight: 'bold',
        marginLeft: 10,
        textDecorationLine: 'underline',
      },
  });

  export default styles;